name: namaz_vaktim
description: Namaz Vaktim baÃ„Å¸Ã„Â±msÃ„Â±z mobil uygulamasÃ„Â±.
publish_to: none
version: 1.7.1+18

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.17
  kapadokya_mobile_core:
    path: ../kapadokya-mobile-core
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  timezone: ^0.9.4
  geolocator: ^13.0.2
  geocoding: ^5.0.0
  package_info_plus: ^8.0.0
  sensors_plus: ^6.1.1
  url_launcher: ^6.3.1
  google_mobile_ads: ^5.3.1
  flutter_timezone: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/app.production.json
    - assets/config/namaz_vaktim_logo.svg
